# Generated by Django 4.2.7 on 2025-09-01 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomacaoComunicacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('novo_membro', 'Novo Membro'), ('aniversario', 'Aniversário'), ('ausencia_culto', 'Ausência no Culto'), ('data_especifica', 'Data Específica'), ('evento_personalizado', 'Evento Personalizado')], max_length=50)),
                ('condicoes', models.JSONField(blank=True, default=dict)),
                ('delay_dias', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Automação de Comunicação',
                'verbose_name_plural': 'Automações de Comunicação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('servidor_smtp', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('porta_smtp', models.IntegerField(default=587)),
                ('usar_tls', models.BooleanField(default=True)),
                ('email_remetente', models.EmailField(max_length=254)),
                ('nome_remetente', models.CharField(max_length=200)),
                ('senha_email', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração de E-mail',
                'verbose_name_plural': 'Configurações de E-mail',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoWhatsApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('api_token', models.CharField(max_length=500)),
                ('numero_telefone', models.CharField(max_length=20)),
                ('webhook_url', models.URLField(blank=True)),
                ('provedor', models.CharField(choices=[('whatsapp_business', 'WhatsApp Business API'), ('twilio', 'Twilio'), ('chatapi', 'ChatAPI'), ('evolution', 'Evolution API')], max_length=50)),
                ('configuracoes_extras', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração do WhatsApp',
                'verbose_name_plural': 'Configurações do WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='ContatoLista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisparoComunicacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification')], max_length=20)),
                ('assunto', models.CharField(blank=True, max_length=200)),
                ('conteudo', models.TextField()),
                ('agendado_para', models.DateTimeField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('total_destinatarios', models.IntegerField(default=0)),
                ('total_enviados', models.IntegerField(default=0)),
                ('total_entregues', models.IntegerField(default=0)),
                ('total_lidos', models.IntegerField(default=0)),
                ('total_erros', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('lido', 'Lido'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
            ],
            options={
                'verbose_name': 'Disparo de Comunicação',
                'verbose_name_plural': 'Disparos de Comunicação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListaContatos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('filtros', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Lista de Contatos',
                'verbose_name_plural': 'Listas de Contatos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LogEnvioMensagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('destinatario', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('lido', 'Lido'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('erro_mensagem', models.TextField(blank=True)),
                ('tentativas', models.IntegerField(default=0)),
                ('id_externo', models.CharField(blank=True, max_length=200)),
                ('webhook_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de Envio',
                'verbose_name_plural': 'Logs de Envio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptInOptOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('aceita_email', models.BooleanField(default=True)),
                ('aceita_sms', models.BooleanField(default=True)),
                ('aceita_whatsapp', models.BooleanField(default=True)),
                ('aceita_push', models.BooleanField(default=True)),
                ('data_opt_in', models.DateTimeField(auto_now_add=True)),
                ('data_opt_out', models.DateTimeField(blank=True, null=True)),
                ('motivo_opt_out', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Preferência de Comunicação',
                'verbose_name_plural': 'Preferências de Comunicação',
            },
        ),
        migrations.CreateModel(
            name='TemplateMensagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification')], max_length=20)),
                ('assunto', models.CharField(blank=True, max_length=200)),
                ('conteudo', models.TextField()),
                ('variaveis_disponiveis', models.JSONField(blank=True, default=list)),
                ('categoria', models.CharField(choices=[('boas_vindas', 'Boas-vindas'), ('aniversario', 'Aniversário'), ('evento', 'Evento'), ('lembrete', 'Lembrete'), ('pastoral', 'Pastoral'), ('financeiro', 'Financeiro'), ('geral', 'Geral')], max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Template de Mensagem',
                'verbose_name_plural': 'Templates de Mensagem',
                'ordering': ['nome'],
            },
        ),
    ]
