# Generated by Django 4.2.7 on 2025-09-01 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
        ('communication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemensagem',
            name='igreja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_mensagem', to='core.igreja'),
        ),
        migrations.AddField(
            model_name='optinoptout',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_comunicacao', to='members.pessoa'),
        ),
        migrations.AddField(
            model_name='logenviomensagem',
            name='disparo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_envio', to='communication.disparocomunicacao'),
        ),
        migrations.AddField(
            model_name='logenviomensagem',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_mensagens', to='members.pessoa'),
        ),
        migrations.AddField(
            model_name='listacontatos',
            name='contatos',
            field=models.ManyToManyField(related_name='listas_contatos', through='communication.ContatoLista', to='members.pessoa'),
        ),
        migrations.AddField(
            model_name='listacontatos',
            name='igreja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_contatos', to='core.igreja'),
        ),
        migrations.AddField(
            model_name='disparocomunicacao',
            name='contatos_individuais',
            field=models.ManyToManyField(blank=True, related_name='disparos_recebidos', to='members.pessoa'),
        ),
        migrations.AddField(
            model_name='disparocomunicacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disparocomunicacao',
            name='igreja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disparos', to='core.igreja'),
        ),
        migrations.AddField(
            model_name='disparocomunicacao',
            name='lista_contatos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.listacontatos'),
        ),
        migrations.AddField(
            model_name='disparocomunicacao',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.templatemensagem'),
        ),
        migrations.AddField(
            model_name='contatolista',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.listacontatos'),
        ),
        migrations.AddField(
            model_name='contatolista',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.pessoa'),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='igreja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_whatsapp', to='core.igreja'),
        ),
        migrations.AddField(
            model_name='configuracaoemail',
            name='igreja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_email', to='core.igreja'),
        ),
        migrations.AddField(
            model_name='automacaocomunicacao',
            name='igreja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automacoes', to='core.igreja'),
        ),
        migrations.AddField(
            model_name='automacaocomunicacao',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.templatemensagem'),
        ),
        migrations.AlterUniqueTogether(
            name='templatemensagem',
            unique_together={('igreja', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='listacontatos',
            unique_together={('igreja', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='contatolista',
            unique_together={('lista', 'pessoa')},
        ),
    ]
