# Generated by Django 4.2.7 on 2025-09-01 19:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('culto', 'Culto'), ('reuniao', 'Reunião'), ('curso', 'Curso'), ('conferencia', 'Conferência'), ('retiro', 'Retiro'), ('evangelismo', 'Evangelismo'), ('social', 'Social'), ('casamento', 'Casamento'), ('funeral', 'Funeral'), ('batismo', 'Batismo'), ('ceia', 'Santa Ceia')], default='culto', max_length=20)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('local', models.CharField(blank=True, max_length=200)),
                ('endereco', models.TextField(blank=True)),
                ('publico', models.BooleanField(default=True)),
                ('requer_inscricao', models.BooleanField(default=False)),
                ('limite_inscricoes', models.IntegerField(blank=True, null=True)),
                ('valor_inscricao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cor', models.CharField(default='#007bff', max_length=7)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/imagens/')),
                ('observacoes', models.TextField(blank=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.campus')),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.igreja')),
                ('ministerio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='members.ministerio')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_responsaveis', to='members.pessoa')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RecursoEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('sala', 'Sala'), ('equipamento', 'Equipamento'), ('veiculo', 'Veículo'), ('material', 'Material')], max_length=50)),
                ('capacidade', models.IntegerField(blank=True, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=200)),
                ('disponivel', models.BooleanField(default=True)),
                ('requer_aprovacao', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='core.campus')),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='core.igreja')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.pessoa')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ReservaRecurso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_aprovadas', to='members.pessoa')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_reservados', to='events.evento')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='events.recursoevento')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_solicitadas', to='members.pessoa')),
            ],
            options={
                'verbose_name': 'Reserva de Recurso',
                'verbose_name_plural': 'Reservas de Recursos',
            },
        ),
        migrations.CreateModel(
            name='PresencaEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('presente', models.BooleanField(default=True)),
                ('horario_chegada', models.DateTimeField(blank=True, null=True)),
                ('horario_saida', models.DateTimeField(blank=True, null=True)),
                ('visitante', models.BooleanField(default=False)),
                ('primeira_visita', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='events.evento')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_eventos', to='members.pessoa')),
            ],
            options={
                'verbose_name': 'Presença no Evento',
                'verbose_name_plural': 'Presenças no Evento',
                'unique_together': {('evento', 'pessoa')},
            },
        ),
        migrations.CreateModel(
            name='InscricaoEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('presente', 'Presente')], default='pendente', max_length=20)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('forma_pagamento', models.CharField(blank=True, max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='events.evento')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_eventos', to='members.pessoa')),
            ],
            options={
                'verbose_name': 'Inscrição no Evento',
                'verbose_name_plural': 'Inscrições no Evento',
                'unique_together': {('evento', 'pessoa')},
            },
        ),
        migrations.CreateModel(
            name='EscalaEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('louvor', 'Louvor'), ('multimidia', 'Multimídia'), ('recepcao', 'Recepção'), ('kids', 'Kids'), ('seguranca', 'Segurança'), ('limpeza', 'Limpeza'), ('estacionamento', 'Estacionamento'), ('diaconia', 'Diaconia')], max_length=20)),
                ('funcao', models.CharField(blank=True, max_length=100)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='events.evento')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_eventos', to='members.pessoa')),
            ],
            options={
                'verbose_name': 'Escala do Evento',
                'verbose_name_plural': 'Escalas do Evento',
                'unique_together': {('evento', 'tipo', 'pessoa')},
            },
        ),
        migrations.CreateModel(
            name='CheckInEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo_qr', models.CharField(max_length=100, unique=True)),
                ('data_checkin', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='events.evento')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins_eventos', to='members.pessoa')),
                ('responsavel_checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_realizados', to='members.pessoa')),
            ],
            options={
                'verbose_name': 'Check-in do Evento',
                'verbose_name_plural': 'Check-ins do Evento',
                'unique_together': {('evento', 'pessoa')},
            },
        ),
    ]
