# Generated by Django 4.2.7 on 2025-09-01 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.TextField(blank=True)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('telefone_residencial', models.CharField(blank=True, max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familias', to='core.campus')),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familias', to='core.igreja')),
            ],
            options={
                'verbose_name': 'Família',
                'verbose_name_plural': 'Famílias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MembroMinisterio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('funcao', models.CharField(choices=[('lider', 'Líder'), ('vice_lider', 'Vice-Líder'), ('secretario', 'Secretário'), ('tesoureiro', 'Tesoureiro'), ('membro', 'Membro')], default='membro', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Membro do Ministério',
                'verbose_name_plural': 'Membros do Ministério',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome_completo', models.CharField(max_length=200)),
                ('nome_preferencia', models.CharField(blank=True, max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20)),
                ('endereco', models.TextField(blank=True)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('escolaridade', models.CharField(blank=True, max_length=50)),
                ('status_membro', models.CharField(choices=[('visitante', 'Visitante'), ('frequentador', 'Frequentador'), ('membro', 'Membro'), ('lider', 'Líder'), ('pastor', 'Pastor'), ('inativo', 'Inativo')], default='visitante', max_length=20)),
                ('data_primeira_visita', models.DateField(blank=True, null=True)),
                ('data_conversao', models.DateField(blank=True, null=True)),
                ('data_batismo', models.DateField(blank=True, null=True)),
                ('data_membresia', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pessoas/fotos/')),
                ('observacoes', models.TextField(blank=True)),
                ('aceite_lgpd', models.BooleanField(default=False)),
                ('data_aceite_lgpd', models.DateTimeField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='core.campus')),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='core.igreja')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome_completo'],
                'unique_together': {('igreja', 'cpf')},
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data_visita', models.DateTimeField()),
                ('tipo_visita', models.CharField(choices=[('pastoral', 'Pastoral'), ('evangelistica', 'Evangelística'), ('social', 'Social'), ('acompanhamento', 'Acompanhamento')], max_length=50)),
                ('motivo', models.TextField()),
                ('observacoes', models.TextField(blank=True)),
                ('proxima_visita', models.DateField(blank=True, null=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='core.igreja')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='members.pessoa')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-data_visita'],
            },
        ),
        migrations.CreateModel(
            name='PedidoOracao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('publico', models.BooleanField(default=False)),
                ('urgente', models.BooleanField(default=False)),
                ('data_resposta', models.DateField(blank=True, null=True)),
                ('testemunho', models.TextField(blank=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_oracao', to='core.igreja')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_oracao', to='members.pessoa')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Oração',
                'verbose_name_plural': 'Pedidos de Oração',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('cor', models.CharField(default='#007bff', max_length=7)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ministerios', to='core.campus')),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministerios', to='core.igreja')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministerios_liderados', to='members.pessoa')),
                ('membros', models.ManyToManyField(related_name='ministerios', through='members.MembroMinisterio', to='members.pessoa')),
            ],
            options={
                'verbose_name': 'Ministério',
                'verbose_name_plural': 'Ministérios',
                'ordering': ['nome'],
                'unique_together': {('igreja', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='membroministerio',
            name='ministerio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.ministerio'),
        ),
        migrations.AddField(
            model_name='membroministerio',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.pessoa'),
        ),
        migrations.AlterUniqueTogether(
            name='membroministerio',
            unique_together={('ministerio', 'pessoa')},
        ),
        migrations.CreateModel(
            name='MembroFamilia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parentesco', models.CharField(choices=[('chefe', 'Chefe da Família'), ('conjuge', 'Cônjuge'), ('filho', 'Filho(a)'), ('pai', 'Pai/Mãe'), ('irmao', 'Irmão/Irmã'), ('outro', 'Outro')], max_length=20)),
                ('responsavel_financeiro', models.BooleanField(default=False)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='members.familia')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familias', to='members.pessoa')),
            ],
            options={
                'verbose_name': 'Membro da Família',
                'verbose_name_plural': 'Membros da Família',
                'unique_together': {('familia', 'pessoa')},
            },
        ),
    ]
