# Generated by Django 4.2.7 on 2025-09-01 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('widgets', models.JSONField(blank=True, default=list)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('publico', models.BooleanField(default=False)),
                ('padrao', models.BooleanField(default=False)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='core.igreja')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('grafico_linha', 'Gráfico de Linha'), ('grafico_barra', 'Gráfico de Barra'), ('grafico_pizza', 'Gráfico de Pizza'), ('contador', 'Contador'), ('tabela', 'Tabela'), ('mapa', 'Mapa'), ('calendario', 'Calendário')], max_length=50)),
                ('configuracao', models.JSONField(blank=True, default=dict)),
                ('posicao_x', models.IntegerField(default=0)),
                ('posicao_y', models.IntegerField(default=0)),
                ('largura', models.IntegerField(default=4)),
                ('altura', models.IntegerField(default=3)),
                ('fonte_dados', models.CharField(blank=True, max_length=200)),
                ('query_personalizada', models.TextField(blank=True)),
                ('atualizar_automatico', models.BooleanField(default=True)),
                ('intervalo_atualizacao', models.IntegerField(default=300)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets_dashboard', to='reports.dashboard')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['posicao_y', 'posicao_x'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioPersonalizado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('membros', 'Membros'), ('presenca', 'Presença'), ('financeiro', 'Financeiro'), ('grupos', 'Grupos'), ('eventos', 'Eventos'), ('comunicacao', 'Comunicação'), ('personalizado', 'Personalizado')], max_length=20)),
                ('query_sql', models.TextField(blank=True)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('campos_exibicao', models.JSONField(blank=True, default=list)),
                ('filtros_disponiveis', models.JSONField(blank=True, default=list)),
                ('publico', models.BooleanField(default=False)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='core.igreja')),
            ],
            options={
                'verbose_name': 'Relatório Personalizado',
                'verbose_name_plural': 'Relatórios Personalizados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoRelatorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parametros_utilizados', models.JSONField(blank=True, default=dict)),
                ('data_execucao', models.DateTimeField(auto_now_add=True)),
                ('tempo_execucao', models.FloatField(blank=True, null=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('arquivo_resultado', models.FileField(blank=True, null=True, upload_to='relatorios/')),
                ('status', models.CharField(choices=[('executando', 'Executando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='executando', max_length=20)),
                ('erro_mensagem', models.TextField(blank=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='reports.relatoriopersonalizado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_executados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execução de Relatório',
                'verbose_name_plural': 'Execuções de Relatórios',
                'ordering': ['-data_execucao'],
            },
        ),
    ]
