# Generated by Django 4.2.7 on 2025-09-01 19:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('celula', 'Célula'), ('grupo_pequeno', 'Grupo Pequeno'), ('classe', 'Classe'), ('ministerio', 'Ministério'), ('departamento', 'Departamento')], default='celula', max_length=20)),
                ('endereco', models.TextField(blank=True)),
                ('dia_reuniao', models.CharField(blank=True, choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('horario_reuniao', models.TimeField(blank=True, null=True)),
                ('meta_membros', models.IntegerField(default=12)),
                ('meta_multiplicacao', models.DateField(blank=True, null=True)),
                ('cor', models.CharField(default='#007bff', max_length=7)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='grupos/fotos/')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='core.campus')),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='core.igreja')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_liderados', to='members.pessoa')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data_reuniao', models.DateTimeField()),
                ('tema', models.CharField(max_length=200)),
                ('versiculo', models.CharField(blank=True, max_length=500)),
                ('resumo', models.TextField(blank=True)),
                ('total_presentes', models.IntegerField(default=0)),
                ('total_visitantes', models.IntegerField(default=0)),
                ('total_conversoes', models.IntegerField(default=0)),
                ('oferta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes', to='groups.grupo')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.pessoa')),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
                'ordering': ['-data_reuniao'],
            },
        ),
        migrations.CreateModel(
            name='MembroGrupo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('lider', 'Líder'), ('vice_lider', 'Vice-Líder'), ('secretario', 'Secretário')], default='ativo', max_length=20)),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.grupo')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.pessoa')),
            ],
            options={
                'verbose_name': 'Membro do Grupo',
                'verbose_name_plural': 'Membros do Grupo',
                'unique_together': {('grupo', 'pessoa')},
            },
        ),
        migrations.CreateModel(
            name='MaterialEstudo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('conteudo', models.TextField()),
                ('categoria', models.CharField(choices=[('celula', 'Célula'), ('discipulado', 'Discipulado'), ('lideranca', 'Liderança'), ('evangelismo', 'Evangelismo'), ('familia', 'Família'), ('jovens', 'Jovens'), ('criancas', 'Crianças')], max_length=50)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='materiais/')),
                ('link_externo', models.URLField(blank=True)),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_estudo', to='core.igreja')),
            ],
            options={
                'verbose_name': 'Material de Estudo',
                'verbose_name_plural': 'Materiais de Estudo',
                'ordering': ['-data_publicacao', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='membros',
            field=models.ManyToManyField(related_name='grupos', through='groups.MembroGrupo', to='members.pessoa'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='vice_lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_vice_liderados', to='members.pessoa'),
        ),
        migrations.CreateModel(
            name='PresencaReuniao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('presente', models.BooleanField(default=True)),
                ('visitante', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_reuniao', to='members.pessoa')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='groups.reuniao')),
            ],
            options={
                'verbose_name': 'Presença na Reunião',
                'verbose_name_plural': 'Presenças na Reunião',
                'unique_together': {('reuniao', 'pessoa')},
            },
        ),
        migrations.CreateModel(
            name='GrupoMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.grupo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.materialestudo')),
            ],
            options={
                'verbose_name': 'Material do Grupo',
                'verbose_name_plural': 'Materiais do Grupo',
                'unique_together': {('grupo', 'material')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('igreja', 'nome')},
        ),
    ]
